// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: business_user_queries.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const syncBusinessUser = `-- name: SyncBusinessUser :exec
INSERT INTO "business_users" (
    user_id,
    business_id,
    role,
    created_at,
    created_by,
    updated_at,
    updated_by,
    deleted_at,
    deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT (user_id, business_id) DO 
UPDATE SET role = $3, created_at = $4, created_by = $5, updated_at = $6, updated_by = $7, deleted_at = $8, deleted_by = $9
`

type SyncBusinessUserParams struct {
	UserID     uuid.UUID  `json:"user_id"`
	BusinessID uuid.UUID  `json:"business_id"`
	Role       string     `json:"role"`
	CreatedAt  time.Time  `json:"created_at"`
	CreatedBy  uuid.UUID  `json:"created_by"`
	UpdatedAt  time.Time  `json:"updated_at"`
	UpdatedBy  *uuid.UUID `json:"updated_by"`
	DeletedAt  *time.Time `json:"deleted_at"`
	DeletedBy  *uuid.UUID `json:"deleted_by"`
}

func (q *Queries) SyncBusinessUser(ctx context.Context, arg SyncBusinessUserParams) error {
	_, err := q.db.Exec(ctx, syncBusinessUser,
		arg.UserID,
		arg.BusinessID,
		arg.Role,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	return err
}
