// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: business_queries.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const syncBusiness = `-- name: SyncBusiness :exec
INSERT INTO "businesses" (
    id,
    name,
    description,
    logo,
    industry,
    primary_currency,
    owner_id,
    currencies,
    created_at,
    created_by,
    updated_at,
    updated_by,
    deleted_at,
    deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14) ON CONFLICT (id) DO 
UPDATE SET name = $2, description = $3, logo = $4, industry = $5, primary_currency = $6, owner_id = $7, currencies = $8, created_at = $9,
created_by = $10, updated_at = $11, updated_by = $12, deleted_at = $13, deleted_by = $14
`

type SyncBusinessParams struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	Description     *string    `json:"description"`
	Logo            *string    `json:"logo"`
	Industry        string     `json:"industry"`
	PrimaryCurrency string     `json:"primary_currency"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	Currencies      []string   `json:"currencies"`
	CreatedAt       time.Time  `json:"created_at"`
	CreatedBy       uuid.UUID  `json:"created_by"`
	UpdatedAt       time.Time  `json:"updated_at"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
	DeletedAt       *time.Time `json:"deleted_at"`
	DeletedBy       *uuid.UUID `json:"deleted_by"`
}

func (q *Queries) SyncBusiness(ctx context.Context, arg SyncBusinessParams) error {
	_, err := q.db.Exec(ctx, syncBusiness,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Logo,
		arg.Industry,
		arg.PrimaryCurrency,
		arg.OwnerID,
		arg.Currencies,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	return err
}
