// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dao

import (
	"time"

	"github.com/google/uuid"
)

type Business struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	Description     *string    `json:"description"`
	Logo            *string    `json:"logo"`
	Industry        string     `json:"industry"`
	PrimaryCurrency string     `json:"primary_currency"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	Currencies      []string   `json:"currencies"`
	CreatedAt       time.Time  `json:"created_at"`
	CreatedBy       uuid.UUID  `json:"created_by"`
	UpdatedAt       time.Time  `json:"updated_at"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
	DeletedAt       *time.Time `json:"deleted_at"`
	DeletedBy       *uuid.UUID `json:"deleted_by"`
}

type BusinessUser struct {
	UserID     uuid.UUID  `json:"user_id"`
	BusinessID uuid.UUID  `json:"business_id"`
	Role       string     `json:"role"`
	CreatedAt  time.Time  `json:"created_at"`
	CreatedBy  uuid.UUID  `json:"created_by"`
	UpdatedAt  time.Time  `json:"updated_at"`
	UpdatedBy  *uuid.UUID `json:"updated_by"`
	DeletedAt  *time.Time `json:"deleted_at"`
	DeletedBy  *uuid.UUID `json:"deleted_by"`
}

type ProductCategory struct {
	ID         uuid.UUID  `json:"id"`
	Name       string     `json:"name"`
	BusinessID uuid.UUID  `json:"business_id"`
	CreatedAt  time.Time  `json:"created_at"`
	CreatedBy  uuid.UUID  `json:"created_by"`
	UpdatedAt  time.Time  `json:"updated_at"`
	UpdatedBy  *uuid.UUID `json:"updated_by"`
	DeletedAt  *time.Time `json:"deleted_at"`
	DeletedBy  *uuid.UUID `json:"deleted_by"`
}

type User struct {
	ID            uuid.UUID  `json:"id"`
	HumanID       string     `json:"human_id"`
	Name          string     `json:"name"`
	Email         string     `json:"email"`
	Dp            *string    `json:"dp"`
	EmailVerified bool       `json:"email_verified"`
	Phone         string     `json:"phone"`
	PhoneVerified bool       `json:"phone_verified"`
	CreatedAt     time.Time  `json:"created_at"`
	CreatedBy     uuid.UUID  `json:"created_by"`
	UpdatedAt     time.Time  `json:"updated_at"`
	UpdatedBy     *uuid.UUID `json:"updated_by"`
	DeactivatedAt *time.Time `json:"deactivated_at"`
	DeactivatedBy *uuid.UUID `json:"deactivated_by"`
	DeletedAt     *time.Time `json:"deleted_at"`
	DeletedBy     *uuid.UUID `json:"deleted_by"`
}
