// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: product_category_queries.sql

package dao

import (
	"context"

	"github.com/google/uuid"
)

const createProductCategory = `-- name: CreateProductCategory :one
INSERT INTO "product_categories" ( name, business_id, created_by) 
VALUES ($1, $2, $3) RETURNING id, name, business_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateProductCategoryParams struct {
	Name       string    `json:"name"`
	BusinessID uuid.UUID `json:"business_id"`
	CreatedBy  uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, createProductCategory, arg.Name, arg.BusinessID, arg.CreatedBy)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const listProductCategoriesByBusinessID = `-- name: ListProductCategoriesByBusinessID :many
SELECT id, name, business_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM "product_categories" WHERE business_id = $1 AND deleted_at IS NULL ORDER BY name ASC LIMIT $2 OFFSET $3
`

type ListProductCategoriesByBusinessIDParams struct {
	BusinessID uuid.UUID `json:"business_id"`
	Limit      int       `json:"limit"`
	Offset     int       `json:"offset"`
}

func (q *Queries) ListProductCategoriesByBusinessID(ctx context.Context, arg ListProductCategoriesByBusinessIDParams) ([]ProductCategory, error) {
	rows, err := q.db.Query(ctx, listProductCategoriesByBusinessID, arg.BusinessID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductCategory
	for rows.Next() {
		var i ProductCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.BusinessID,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.DeletedAt,
			&i.DeletedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setProductCategoryNameByID = `-- name: SetProductCategoryNameByID :one
UPDATE "product_categories" 
SET name = $2, updated_at = now(), updated_by = $3
WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, business_id, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type SetProductCategoryNameByIDParams struct {
	ID        uuid.UUID  `json:"id"`
	Name      string     `json:"name"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SetProductCategoryNameByID(ctx context.Context, arg SetProductCategoryNameByIDParams) (ProductCategory, error) {
	row := q.db.QueryRow(ctx, setProductCategoryNameByID, arg.ID, arg.Name, arg.UpdatedBy)
	var i ProductCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.BusinessID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
