// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dao

import (
	"context"
)

type Querier interface {
	CreateProductCategory(ctx context.Context, arg CreateProductCategoryParams) (ProductCategory, error)
	ListProductCategoriesByBusinessID(ctx context.Context, arg ListProductCategoriesByBusinessIDParams) ([]ProductCategory, error)
	SetProductCategoryNameByID(ctx context.Context, arg SetProductCategoryNameByIDParams) (ProductCategory, error)
	SyncBusiness(ctx context.Context, arg SyncBusinessParams) error
	SyncBusinessUser(ctx context.Context, arg SyncBusinessUserParams) error
	SyncUser(ctx context.Context, arg SyncUserParams) error
}

var _ Querier = (*Queries)(nil)
