// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: user_queries.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const syncUser = `-- name: SyncUser :exec
INSERT INTO users (
  id,
  human_id,
  name,
  email,
  dp,
  email_verified,
  phone,
  phone_verified,
  created_at,
  created_by,
  updated_at,
  updated_by,
  deactivated_at,
  deactivated_by,
  deleted_at,
  deleted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16) ON CONFLICT (id) DO 
UPDATE SET human_id = $2, name = $3, email = $4, dp = $5, email_verified = $6, phone = $7, 
 phone_verified = $8, created_at = $9,
 created_by = $10, updated_at = $11, updated_by = $12, deactivated_at = $13, deactivated_by = $14,
 deleted_at = $15, deleted_by = $16
`

type SyncUserParams struct {
	ID            uuid.UUID  `json:"id"`
	HumanID       string     `json:"human_id"`
	Name          string     `json:"name"`
	Email         string     `json:"email"`
	Dp            *string    `json:"dp"`
	EmailVerified bool       `json:"email_verified"`
	Phone         string     `json:"phone"`
	PhoneVerified bool       `json:"phone_verified"`
	CreatedAt     time.Time  `json:"created_at"`
	CreatedBy     uuid.UUID  `json:"created_by"`
	UpdatedAt     time.Time  `json:"updated_at"`
	UpdatedBy     *uuid.UUID `json:"updated_by"`
	DeactivatedAt *time.Time `json:"deactivated_at"`
	DeactivatedBy *uuid.UUID `json:"deactivated_by"`
	DeletedAt     *time.Time `json:"deleted_at"`
	DeletedBy     *uuid.UUID `json:"deleted_by"`
}

func (q *Queries) SyncUser(ctx context.Context, arg SyncUserParams) error {
	_, err := q.db.Exec(ctx, syncUser,
		arg.ID,
		arg.HumanID,
		arg.Name,
		arg.Email,
		arg.Dp,
		arg.EmailVerified,
		arg.Phone,
		arg.PhoneVerified,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeactivatedAt,
		arg.DeactivatedBy,
		arg.DeletedAt,
		arg.DeletedBy,
	)
	return err
}
