CREATE TABLE "invitations" (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    business_id uuid NOT NULL,
    hash text NOT NULL,
    expires_at timestamptz NOT NULL,
    accepted_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by uuid NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP,
    updated_by uuid,
    deleted_at timestamptz,
    deleted_by uuid,
    FOREIGN KEY ("business_id") REFERENCES "businesses"("id"),
    FOREIGN KEY ("created_by") REFERENCES "users"("id"),
    FOREIGN KEY ("updated_by") REFERENCES "users"("id"),
    FOREIGN KEY ("deleted_by") REFERENCES "users"("id")
);