# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  kafka:up:
    cmds:
      - docker-compose -f ./kafka/docker-compose.yml up -d
  kafka:down:
    cmds:
      - docker-compose -f ./kafka/docker-compose.yml down
  postgres:up:
    cmds:
      - docker-compose -f ./postgres/docker-compose.yml up -d
  postgres:down:
    cmds:
      - docker-compose -f ./postgres/docker-compose.yml down
  mongodb:up:
    cmds:
      - docker-compose -f ./mongodb/docker-compose.yml up -d
  mongodb:down:
    cmds:
      - docker-compose -f ./mongodb/docker-compose.yml down
  mailhog:up:
    cmds:
      - docker-compose -f ./mailhog/docker-compose.yml up -d
  mailhog:down:
    cmds:
      - docker-compose -f ./mailhog/docker-compose.yml down
  all:up:
    cmds:
      - task: kafka:up
      - task: postgres:up
      - task: mongodb:up
      - task: mailhog:up
  all:down:
    cmds:
      - task: kafka:down
      - task: postgres:down
      - task: mongodb:down
      - task: mailhog:down