// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: business_queries.sql

package dao

import (
	"context"

	"github.com/google/uuid"
)

const createBusiness = `-- name: CreateBusiness :one
INSERT INTO "businesses" (
    name, description, logo, industry, primary_currency, owner_id, currencies, created_by
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, name, description, logo, industry, primary_currency, owner_id, currencies, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateBusinessParams struct {
	Name            string    `json:"name"`
	Description     *string   `json:"description"`
	Logo            *string   `json:"logo"`
	Industry        string    `json:"industry"`
	PrimaryCurrency string    `json:"primary_currency"`
	OwnerID         uuid.UUID `json:"owner_id"`
	Currencies      []string  `json:"currencies"`
	CreatedBy       uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateBusiness(ctx context.Context, arg CreateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, createBusiness,
		arg.Name,
		arg.Description,
		arg.Logo,
		arg.Industry,
		arg.PrimaryCurrency,
		arg.OwnerID,
		arg.Currencies,
		arg.CreatedBy,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.PrimaryCurrency,
		&i.OwnerID,
		&i.Currencies,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const deleteBusiness = `-- name: DeleteBusiness :one
DELETE FROM "businesses" WHERE id = $1 AND deleted_at IS NULL RETURNING id, name, description, logo, industry, primary_currency, owner_id, currencies, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

func (q *Queries) DeleteBusiness(ctx context.Context, id uuid.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, deleteBusiness, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.PrimaryCurrency,
		&i.OwnerID,
		&i.Currencies,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const findBusinessById = `-- name: FindBusinessById :one
SELECT id, name, description, logo, industry, primary_currency, owner_id, currencies, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM "businesses" WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) FindBusinessById(ctx context.Context, id uuid.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, findBusinessById, id)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.PrimaryCurrency,
		&i.OwnerID,
		&i.Currencies,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const findBusinessByOwner = `-- name: FindBusinessByOwner :one
SELECT id, name, description, logo, industry, primary_currency, owner_id, currencies, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM "businesses" WHERE owner_id = $1 AND deleted_at IS NULL
`

func (q *Queries) FindBusinessByOwner(ctx context.Context, ownerID uuid.UUID) (Business, error) {
	row := q.db.QueryRow(ctx, findBusinessByOwner, ownerID)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.PrimaryCurrency,
		&i.OwnerID,
		&i.Currencies,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const setBusinessLogo = `-- name: SetBusinessLogo :one
UPDATE "businesses" SET
    logo = $2,
    updated_by = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, logo, industry, primary_currency, owner_id, currencies, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type SetBusinessLogoParams struct {
	ID        uuid.UUID  `json:"id"`
	Logo      *string    `json:"logo"`
	UpdatedBy *uuid.UUID `json:"updated_by"`
}

func (q *Queries) SetBusinessLogo(ctx context.Context, arg SetBusinessLogoParams) (Business, error) {
	row := q.db.QueryRow(ctx, setBusinessLogo, arg.ID, arg.Logo, arg.UpdatedBy)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.PrimaryCurrency,
		&i.OwnerID,
		&i.Currencies,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const updateBusiness = `-- name: UpdateBusiness :one
UPDATE "businesses" SET
    name = $2,
    description = $3,
    logo = $4,
    industry = $5,
    primary_currency = $6,
    currencies = $7,
    updated_by = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, name, description, logo, industry, primary_currency, owner_id, currencies, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type UpdateBusinessParams struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	Description     *string    `json:"description"`
	Logo            *string    `json:"logo"`
	Industry        string     `json:"industry"`
	PrimaryCurrency string     `json:"primary_currency"`
	Currencies      []string   `json:"currencies"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
}

func (q *Queries) UpdateBusiness(ctx context.Context, arg UpdateBusinessParams) (Business, error) {
	row := q.db.QueryRow(ctx, updateBusiness,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Logo,
		arg.Industry,
		arg.PrimaryCurrency,
		arg.Currencies,
		arg.UpdatedBy,
	)
	var i Business
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Logo,
		&i.Industry,
		&i.PrimaryCurrency,
		&i.OwnerID,
		&i.Currencies,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
