// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: invitation_queries.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO "invitations" (
  name, email, phone, business_id, hash, expires_at, created_by
) VAlUES (
  $1,$2,$3,$4,$5,$6,$7
) RETURNING id, name, email, phone, business_id, hash, expires_at, accepted_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by
`

type CreateInvitationParams struct {
	Name       string    `json:"name"`
	Email      string    `json:"email"`
	Phone      string    `json:"phone"`
	BusinessID uuid.UUID `json:"business_id"`
	Hash       string    `json:"hash"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedBy  uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.Name,
		arg.Email,
		arg.Phone,
		arg.BusinessID,
		arg.Hash,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BusinessID,
		&i.Hash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const findInvitationByHashAndBusinessID = `-- name: FindInvitationByHashAndBusinessID :one
SELECT id, name, email, phone, business_id, hash, expires_at, accepted_at, created_at, created_by, updated_at, updated_by, deleted_at, deleted_by FROM "invitations" WHERE hash = $1 AND business_id = $2 AND expires_at > now() AND deleted_at IS NULL
`

type FindInvitationByHashAndBusinessIDParams struct {
	Hash       string    `json:"hash"`
	BusinessID uuid.UUID `json:"business_id"`
}

func (q *Queries) FindInvitationByHashAndBusinessID(ctx context.Context, arg FindInvitationByHashAndBusinessIDParams) (Invitation, error) {
	row := q.db.QueryRow(ctx, findInvitationByHashAndBusinessID, arg.Hash, arg.BusinessID)
	var i Invitation
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Phone,
		&i.BusinessID,
		&i.Hash,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const setInvitationAcceptedAt = `-- name: SetInvitationAcceptedAt :exec
UPDATE "invitations" SET accepted_at = CURRENT_TIMESTAMP WHERE id = $1 AND accepted_at IS NULL AND deleted_at IS NULL
`

func (q *Queries) SetInvitationAcceptedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setInvitationAcceptedAt, id)
	return err
}
