// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package dao

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
)

type VerificationType string

const (
	VerificationTypeEmail         VerificationType = "email"
	VerificationTypePhone         VerificationType = "phone"
	VerificationTypeResetPassword VerificationType = "reset_password"
	VerificationTypeChangeEmail   VerificationType = "change_email"
	VerificationTypeChangePhone   VerificationType = "change_phone"
)

func (e *VerificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationType(s)
	case string:
		*e = VerificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationType: %T", src)
	}
	return nil
}

type NullVerificationType struct {
	VerificationType VerificationType `json:"verification_type"`
	Valid            bool             `json:"valid"` // Valid is true if VerificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationType) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationType), nil
}

func AllVerificationTypeValues() []VerificationType {
	return []VerificationType{
		VerificationTypeEmail,
		VerificationTypePhone,
		VerificationTypeResetPassword,
		VerificationTypeChangeEmail,
		VerificationTypeChangePhone,
	}
}

type Business struct {
	ID              uuid.UUID  `json:"id"`
	Name            string     `json:"name"`
	Description     *string    `json:"description"`
	Logo            *string    `json:"logo"`
	Industry        string     `json:"industry"`
	PrimaryCurrency string     `json:"primary_currency"`
	OwnerID         uuid.UUID  `json:"owner_id"`
	Currencies      []string   `json:"currencies"`
	CreatedAt       time.Time  `json:"created_at"`
	CreatedBy       uuid.UUID  `json:"created_by"`
	UpdatedAt       time.Time  `json:"updated_at"`
	UpdatedBy       *uuid.UUID `json:"updated_by"`
	DeletedAt       *time.Time `json:"deleted_at"`
	DeletedBy       *uuid.UUID `json:"deleted_by"`
}

type BusinessUser struct {
	UserID     uuid.UUID  `json:"user_id"`
	BusinessID uuid.UUID  `json:"business_id"`
	Role       string     `json:"role"`
	CreatedAt  time.Time  `json:"created_at"`
	CreatedBy  uuid.UUID  `json:"created_by"`
	UpdatedAt  time.Time  `json:"updated_at"`
	UpdatedBy  *uuid.UUID `json:"updated_by"`
	DeletedAt  *time.Time `json:"deleted_at"`
	DeletedBy  *uuid.UUID `json:"deleted_by"`
}

type Password struct {
	ID        uuid.UUID  `json:"id"`
	UserID    uuid.UUID  `json:"user_id"`
	Password  string     `json:"password"`
	CreatedAt time.Time  `json:"created_at"`
	CreatedBy uuid.UUID  `json:"created_by"`
	DeletedAt *time.Time `json:"deleted_at"`
	DeletedBy *uuid.UUID `json:"deleted_by"`
}

type Session struct {
	ID           uuid.UUID  `json:"id"`
	HumanID      string     `json:"human_id"`
	UserIp       string     `json:"user_ip"`
	UserAgent    string     `json:"user_agent"`
	RefreshToken string     `json:"refresh_token"`
	UserID       uuid.UUID  `json:"user_id"`
	ExpiresAt    time.Time  `json:"expires_at"`
	CreatedAt    time.Time  `json:"created_at"`
	CreatedBy    uuid.UUID  `json:"created_by"`
	DeletedAt    *time.Time `json:"deleted_at"`
	DeletedBy    *uuid.UUID `json:"deleted_by"`
}

type User struct {
	ID            uuid.UUID  `json:"id"`
	HumanID       string     `json:"human_id"`
	Name          string     `json:"name"`
	Email         string     `json:"email"`
	Dp            *string    `json:"dp"`
	EmailVerified bool       `json:"email_verified"`
	Phone         string     `json:"phone"`
	PhoneVerified bool       `json:"phone_verified"`
	CreatedAt     time.Time  `json:"created_at"`
	CreatedBy     uuid.UUID  `json:"created_by"`
	UpdatedAt     time.Time  `json:"updated_at"`
	UpdatedBy     *uuid.UUID `json:"updated_by"`
	DeactivatedAt *time.Time `json:"deactivated_at"`
	DeactivatedBy *uuid.UUID `json:"deactivated_by"`
	DeletedAt     *time.Time `json:"deleted_at"`
	DeletedBy     *uuid.UUID `json:"deleted_by"`
}

type VerificationRequest struct {
	ID         uuid.UUID        `json:"id"`
	UserID     uuid.UUID        `json:"user_id"`
	Type       VerificationType `json:"type"`
	Code       string           `json:"code"`
	ExpiresAt  time.Time        `json:"expires_at"`
	CreatedAt  time.Time        `json:"created_at"`
	CreatedBy  uuid.UUID        `json:"created_by"`
	ConsumedAt *time.Time       `json:"consumed_at"`
}
