// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: password_queries.sql

package dao

import (
	"context"

	"github.com/google/uuid"
)

const createPassword = `-- name: CreatePassword :exec
INSERT INTO "passwords" ("user_id", "password","created_by")
VALUES ($1, $2, $3)
`

type CreatePasswordParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Password  string    `json:"password"`
	CreatedBy uuid.UUID `json:"created_by"`
}

func (q *Queries) CreatePassword(ctx context.Context, arg CreatePasswordParams) error {
	_, err := q.db.Exec(ctx, createPassword, arg.UserID, arg.Password, arg.CreatedBy)
	return err
}

const deletePassword = `-- name: DeletePassword :execrows
DELETE FROM "passwords" WHERE "user_id" = $1 AND "deleted_at" IS NULL
`

func (q *Queries) DeletePassword(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deletePassword, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findPasswordByUserId = `-- name: FindPasswordByUserId :one
SELECT id, user_id, password, created_at, created_by, deleted_at, deleted_by FROM "passwords" WHERE "user_id" = $1 AND "deleted_at" IS NULL
`

func (q *Queries) FindPasswordByUserId(ctx context.Context, userID uuid.UUID) (Password, error) {
	row := q.db.QueryRow(ctx, findPasswordByUserId, userID)
	var i Password
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Password,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
