// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: session_queries.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO "sessions" (
  human_id, user_id, user_ip, user_agent, business_id, refresh_token, expires_at, created_by
) VALUES (
   $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, human_id, user_ip, user_agent, refresh_token, user_id, business_id, expires_at, created_at, created_by, deleted_at, deleted_by
`

type CreateSessionParams struct {
	HumanID      string     `json:"human_id"`
	UserID       uuid.UUID  `json:"user_id"`
	UserIp       string     `json:"user_ip"`
	UserAgent    string     `json:"user_agent"`
	BusinessID   *uuid.UUID `json:"business_id"`
	RefreshToken string     `json:"refresh_token"`
	ExpiresAt    time.Time  `json:"expires_at"`
	CreatedBy    uuid.UUID  `json:"created_by"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.HumanID,
		arg.UserID,
		arg.UserIp,
		arg.UserAgent,
		arg.BusinessID,
		arg.RefreshToken,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
UPDATE "sessions" SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const findSessionByRefreshToken = `-- name: FindSessionByRefreshToken :one
SELECT id, human_id, user_ip, user_agent, refresh_token, user_id, business_id, expires_at, created_at, created_by, deleted_at, deleted_by FROM "sessions" WHERE refresh_token = $1 AND expires_at > CURRENT_TIMESTAMP AND deleted_at IS NULL
`

func (q *Queries) FindSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.HumanID,
		&i.UserIp,
		&i.UserAgent,
		&i.RefreshToken,
		&i.UserID,
		&i.BusinessID,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
