// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: verification_request_queries.sql

package dao

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createVerificationRequest = `-- name: CreateVerificationRequest :exec
INSERT INTO "verification_requests" ("user_id", "type", "code", "expires_at", "created_by")
VALUES ($1, $2, $3, $4, $5)
`

type CreateVerificationRequestParams struct {
	UserID    uuid.UUID        `json:"user_id"`
	Type      VerificationType `json:"type"`
	Code      string           `json:"code"`
	ExpiresAt time.Time        `json:"expires_at"`
	CreatedBy uuid.UUID        `json:"created_by"`
}

func (q *Queries) CreateVerificationRequest(ctx context.Context, arg CreateVerificationRequestParams) error {
	_, err := q.db.Exec(ctx, createVerificationRequest,
		arg.UserID,
		arg.Type,
		arg.Code,
		arg.ExpiresAt,
		arg.CreatedBy,
	)
	return err
}

const findVerificationRequestByUserIdAndType = `-- name: FindVerificationRequestByUserIdAndType :one
SELECT id, user_id, type, code, expires_at, created_at, created_by, consumed_at FROM "verification_requests" WHERE "user_id" = $1 AND "type" = $2 
AND "expires_at" > CURRENT_TIMESTAMP AND "consumed_at" IS NULL ORDER BY "created_at" DESC LIMIT 1
`

type FindVerificationRequestByUserIdAndTypeParams struct {
	UserID uuid.UUID        `json:"user_id"`
	Type   VerificationType `json:"type"`
}

func (q *Queries) FindVerificationRequestByUserIdAndType(ctx context.Context, arg FindVerificationRequestByUserIdAndTypeParams) (VerificationRequest, error) {
	row := q.db.QueryRow(ctx, findVerificationRequestByUserIdAndType, arg.UserID, arg.Type)
	var i VerificationRequest
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.ConsumedAt,
	)
	return i, err
}

const setVerificationRequestConsumedAt = `-- name: SetVerificationRequestConsumedAt :exec
UPDATE "verification_requests" SET "consumed_at" = CURRENT_TIMESTAMP WHERE "id" = $1 AND "consumed_at" IS NULL
`

func (q *Queries) SetVerificationRequestConsumedAt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setVerificationRequestConsumedAt, id)
	return err
}
