// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID           uuid.UUID  `json:"id"`
	HumanID      string     `json:"human_id"`
	UserIp       string     `json:"user_ip"`
	UserAgent    string     `json:"user_agent"`
	RefreshToken string     `json:"refresh_token"`
	UserID       uuid.UUID  `json:"user_id"`
	CreatedAt    time.Time  `json:"created_at"`
	CreatedBy    uuid.UUID  `json:"created_by"`
	DeletedAt    *time.Time `json:"deleted_at"`
	DeletedBy    *uuid.UUID `json:"deleted_by"`
}

type User struct {
	ID            uuid.UUID   `json:"id"`
	HumanID       string      `json:"human_id"`
	Name          string      `json:"name"`
	Email         string      `json:"email"`
	Dp            pgtype.Text `json:"dp"`
	EmailVerified bool        `json:"email_verified"`
	Phone         string      `json:"phone"`
	PhoneVerified bool        `json:"phone_verified"`
	Password      string      `json:"password"`
	CreatedAt     time.Time   `json:"created_at"`
	CreatedBy     uuid.UUID   `json:"created_by"`
	UpdatedAt     time.Time   `json:"updated_at"`
	UpdatedBy     uuid.UUID   `json:"updated_by"`
	DeactivatedAt *time.Time  `json:"deactivated_at"`
	DeactivatedBy *uuid.UUID  `json:"deactivated_by"`
	DeletedAt     *time.Time  `json:"deleted_at"`
	DeletedBy     *uuid.UUID  `json:"deleted_by"`
}
