// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO "sessions" (
  human_id, user_id, user_ip, user_agent, refresh_token, created_by
) VALUES (
   $1, $2, $3, $4, $5, $6
) RETURNING id, human_id, user_ip, user_agent, refresh_token, user_id, created_at, created_by, deleted_at, deleted_by
`

type CreateSessionParams struct {
	HumanID      string    `json:"human_id"`
	UserID       uuid.UUID `json:"user_id"`
	UserIp       string    `json:"user_ip"`
	UserAgent    string    `json:"user_agent"`
	RefreshToken string    `json:"refresh_token"`
	CreatedBy    uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.HumanID,
		arg.UserID,
		arg.UserIp,
		arg.UserAgent,
		arg.RefreshToken,
		arg.CreatedBy,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
UPDATE "sessions" SET deleted_at = CURRENT_TIMESTAMP WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const findSessionByRefreshToken = `-- name: FindSessionByRefreshToken :one
SELECT id, human_id, user_ip, user_agent, refresh_token, user_id, created_at, created_by, deleted_at, deleted_by FROM "sessions" WHERE refresh_token = $1 AND deleted_at IS NULL
`

func (q *Queries) FindSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error) {
	row := q.db.QueryRow(ctx, findSessionByRefreshToken, refreshToken)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.HumanID,
		&i.UserIp,
		&i.UserAgent,
		&i.RefreshToken,
		&i.UserID,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
