// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_queries.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const activateUser = `-- name: ActivateUser :exec
UPDATE "users" SET deactivated_at = NULL AND updated_by = $2 WHERE id = $1 AND deactivated_at IS NOT NULL AND deleted_at IS NULL
`

type ActivateUserParams struct {
	ID        uuid.UUID `json:"id"`
	UpdatedBy uuid.UUID `json:"updated_by"`
}

func (q *Queries) ActivateUser(ctx context.Context, arg ActivateUserParams) error {
	_, err := q.db.Exec(ctx, activateUser, arg.ID, arg.UpdatedBy)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO "users" (
   human_id, name, email, email_verified,  phone, password, created_by
) VALUES (
   $1, $2, $3, $4, $5, $6, $7
) RETURNING id, human_id, name, email, dp, email_verified, phone, phone_verified, password, created_at, created_by, updated_at, updated_by, deactivated_at, deactivated_by, deleted_at, deleted_by
`

type CreateUserParams struct {
	HumanID       string    `json:"human_id"`
	Name          string    `json:"name"`
	Email         string    `json:"email"`
	EmailVerified bool      `json:"email_verified"`
	Phone         string    `json:"phone"`
	Password      string    `json:"password"`
	CreatedBy     uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.HumanID,
		arg.Name,
		arg.Email,
		arg.EmailVerified,
		arg.Phone,
		arg.Password,
		arg.CreatedBy,
	)
	return err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE "users" SET deactivated_at = CURRENT_TIMESTAMP AND deactivated_by = $2 WHERE id = $1 AND deactivated_at IS NULL AND deleted_at IS NULL
`

type DeactivateUserParams struct {
	ID            uuid.UUID  `json:"id"`
	DeactivatedBy *uuid.UUID `json:"deactivated_by"`
}

func (q *Queries) DeactivateUser(ctx context.Context, arg DeactivateUserParams) error {
	_, err := q.db.Exec(ctx, deactivateUser, arg.ID, arg.DeactivatedBy)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE "users" SET deleted_at = CURRENT_TIMESTAMP AND deleted_by = $2 WHERE id = $1 AND deleted_at IS NULL
`

type DeleteUserParams struct {
	ID        uuid.UUID  `json:"id"`
	DeletedBy *uuid.UUID `json:"deleted_by"`
}

func (q *Queries) DeleteUser(ctx context.Context, arg DeleteUserParams) error {
	_, err := q.db.Exec(ctx, deleteUser, arg.ID, arg.DeletedBy)
	return err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, human_id, name, email, dp, email_verified, phone, phone_verified, password, created_at, created_by, updated_at, updated_by, deactivated_at, deactivated_by, deleted_at, deleted_by FROM "users" WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HumanID,
		&i.Name,
		&i.Email,
		&i.Dp,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Password,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeactivatedAt,
		&i.DeactivatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}

const findUserById = `-- name: FindUserById :one
SELECT id, human_id, name, email, dp, email_verified, phone, phone_verified, password, created_at, created_by, updated_at, updated_by, deactivated_at, deactivated_by, deleted_at, deleted_by FROM "users" WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) FindUserById(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.HumanID,
		&i.Name,
		&i.Email,
		&i.Dp,
		&i.EmailVerified,
		&i.Phone,
		&i.PhoneVerified,
		&i.Password,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.DeactivatedAt,
		&i.DeactivatedBy,
		&i.DeletedAt,
		&i.DeletedBy,
	)
	return i, err
}
